target_rules:
  pitch_hist: [0.5, 0., 0., 0., 0.25, 0., 0., 0.25, 0., 0., 0., 0.]
  vertical_nd: [3., 3., 3., 3., 3., 3., 3., 3.]
  horizontal_nd: [15., 15., 15., 15., 15., 15., 15., 15.]

guidance:
  vae: True  # whether need to decode during sampling process
  nn: False   # whether to use classifier
  scg: True
  method: no_guidance
  cond_fn: Null
  schedule: True
  t_start: 750   # when to start use guidance
  t_end: 0   # when to end use guidance
  interval: 1  # interval between successive guidance step
  dc:
    base: 128  # The base length to select noise

scg:
  num_samples: 16
  # weight for different losses
  pitch_hist: 100.
  note_density: 1.

sampling:
  use_ddim: False
  diff_collage: True
  t_end: 0  # early stopping for ddpm

dc:
  type: circle
  overlap_size: 64   # how much overlap
  num_img: 1   # how many square images
