target_rules:
  chord_progression: Null

guidance:
  vae: False  # whether need to decode during sampling process
  nn: True   # whether to use classifier
  beam: False
  method: classifier_guidance
  cond_fn:
    rule_names: ['chord_progression']
    fns: ['grad_nn_zt_chord']
    classifier_scales: [10.]
    classifiers:
      num_classes: [8]
      names: ['DiTRotary-S/8-chord-cls']
      paths: ['loggings/classifier/chord-s-allt/model004999.pt']
  schedule: False

sampling:
  use_ddim: False
  diff_collage: False
  t_end: 0  # early stopping for ddpm
