target_rules:
  pitch_hist: Null

guidance:
  vae: False  # whether need to decode during sampling process
  nn: True   # whether to use classifier
  beam: False
  method: classifier_guidance
  cond_fn:
    rule_names: ['pitch_hist']
    fns: ['grad_nn_zt_mse']
    classifier_scales: [400.]
    classifiers:
      num_classes: [12]
      names: ['DiTRotary-S/8-cls']
      paths: ['loggings/classifier/pitch-s-long-allt/model009999.pt']
  schedule: False

sampling:
  use_ddim: False
  diff_collage: False
  t_end: 0  # early stopping for ddpm
