model:
  base_learning_rate: 4.5e-6
  target: taming.models.klvae_pedal.AutoencoderKL
  params:
    embed_dim: 4
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 128
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,2,2,4]  # num_down = len(ch_mult)-1, f = 2^num_down
      num_res_blocks: 2
      attn_resolutions: [] # this needs to be the last layer
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.contperceptual.LPIPSWithDiscriminator
      params:
        disc_start: 100000
        kl_weight: 1.0e-2
        disc_weight: 0
        disc_in_channels: 3
        perceptual_weight: 0.0

data:
  target: taming.main.DataModuleFromConfig
  params:
    batch_size: 128
    num_workers: 16
    train:
      target: taming.data.piano_roll.PRTrain
      params:
        training_images_list_file: /home/train.txt
        size: 128
    validation:
      target: taming.data.piano_roll.PRTest
      params:
        test_images_list_file: /home/test.txt
        size: 128

