target_rules:
  pitch_hist: Null

guidance:
  vae: True  # whether need to decode during sampling process
  nn: False   # whether to use classifier
  scg: False
  method: dps
  schedule: False
  step_size: 1.  # need to tune step size for dps
  cond_fn:
    rule_names: ['pitch_hist']
    fns: ['rule_x0_mse_dummy']
    classifier_scales: [1.]   # use the balance different loss, not for step size

sampling:
  use_ddim: False
  diff_collage: False
  t_end: 0  # early stopping for ddpm
