target_rules:
  pitch_hist: Null
  vertical_nd: Null
  horizontal_nd: Null
  chord_progression: Null

guidance:
  vae: False  # whether need to decode during sampling process
  nn: True   # whether to use classifier
  scg: False
  method: classifier_guidance
  cond_fn:
    rule_names: ['pitch_hist', 'note_density', 'chord_progression']
    fns: ['grad_nn_zt_mse', 'grad_nn_zt_mse', 'grad_nn_zt_chord']
    classifier_scales: [400, 10., 10.]
    classifiers:
      num_classes: [12, 16, 8]
      names: ['DiTRotary-S/8-cls', 'DiTRotary-S/8-cls', 'DiTRotary-S/8-chord-cls']
      paths: ['loggings/classifier/pitch/model009999.pt', 'loggings/classifier/nd/model009999.pt', 'loggings/classifier/chord/model004999.pt']
  schedule: False

sampling:
  use_ddim: False
  diff_collage: False
  t_end: 0  # early stopping for ddpm
