target_rules:
  chord_progression: Null

guidance:
  vae: False  # whether need to decode during sampling process
  nn: True   # whether to use classifier
  beam: False
  method: dps
  schedule: False
  step_size: 1.  # need to tune step size for dps
  cond_fn:
    rule_names: ['chord_progression']
    fns: ['nn_z0_chord_dummy']
    classifier_scales: [1.]   # use the balance different loss, not for step size
    classifiers:
      num_classes: [8]
      names: ['DiTRotary-S/8-chord-cls']
      paths: ['loggings/classifier/chord-s-allt/model004999.pt']

sampling:
  use_ddim: False
  diff_collage: False
  t_end: 0  # early stopping for ddpm
