target_rules:
  vertical_nd: Null
  horizontal_nd: Null

guidance:
  vae: True  # whether need to decode during sampling process
  nn: False   # whether to use classifier
  scg: True
  method: no_guidance
  cond_fn: Null
  schedule: False

scg:
  num_samples: 16

sampling:
  diff_collage: False
  t_end: 0  # early stopping for ddpm
  use_ddim: True
  timestep_respacing: ddim25
