target_rules:
  pitch_hist: Null
  vertical_nd: Null
  horizontal_nd: Null
  chord_progression: Null

guidance:
  vae: True  # whether need to decode during sampling process
  nn: True   # whether to use classifier
  scg: True
  method: classifier_guidance
  cond_fn:
    rule_names: ['pitch_hist', 'note_density', 'chord_progression']
    fns: ['grad_nn_zt_mse', 'grad_nn_zt_mse', 'grad_nn_zt_chord']
    classifier_scales: [400, 10., 10.]
    classifiers:
      num_classes: [12, 16, 8]
      names: ['DiTRotary-S/8-cls', 'DiTRotary-S/8-cls', 'DiTRotary-S/8-chord-cls']
      paths: ['loggings/classifier/pitch-s-long-allt/model009999.pt', 'loggings/classifier/nd-s-long-allt/model009999.pt', 'loggings/classifier/chord-s-allt/model004999.pt']
  schedule: True
  t_start: 750   # when to start use guidance
  t_end: 0   # when to end use guidance
  interval: 1  # interval between successive guidance step

scg:
  num_samples: 4
  # weight for different losses
  pitch_hist: 40.
  note_density: 1.
  chord_progression: 4.

sampling:
  use_ddim: False
  diff_collage: False
  t_end: 0  # early stopping for ddpm

