target_rules:
  chord_progression: Null

guidance:
  vae: False  # whether need to decode during sampling process
  nn: False   # whether to use classifier
  scg: False
  method: no_guidance
  cond_fn: Null
  schedule: False

sampling:
  use_ddim: False
  diff_collage: False
  t_end: 0  # early stopping for ddpm
