target_rules:
  vertical_nd: Null
  horizontal_nd: Null

guidance:
  vae: True  # whether need to decode during sampling process
  nn: False   # whether to use classifier
  scg: True
  method: no_guidance
  cond_fn: Null
  schedule: True
  t_start: 750   # when to start use guidance
  t_end: 0   # when to end use guidance
  interval: 1  # interval between successive guidance step

scg:
  num_samples: 16

sampling:
  use_ddim: False
  diff_collage: False
  t_end: 300  # early stopping for ddpm
